openapi: 3.0.1
info:
  title: Engines WS APIs
  description: creation of engine data and running of the respective engine
  version: '0.1'
tags:
  - name: RTT
    description: Real Time Engine
paths:
  /engines/rtt:
    post:
      tags:
        - RTT
      description: Web Service to pass data to and run the Real Time Engine
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RTT:
                  type: array
                  items:
                    type: object
            examples:
              'sample':
                value:
                  RTTInbound:
                    requestID: '99999'
                    tableGroupID: 0
                    removePriorRecords: 'N'
                    investigateErrors: 'Y'
                    ICPriceMandatory: 'N'
                    transactions:
                      - sourceAssignmentName: Vision Comms RT
                        transactionTable: REAL TIME
                        transactionType: TYPE
                        transactionClass: CLASS
                        transactionRef: MSS90687
                        transactionID: 90988
                        parentTrxID: 90985
                        transactionDate: 01-JAN-2021
                        currencyCode: USD
                        attribute1: '01'
                        attribute2: '03'
                        attribute3: Service
                        enteredDR: 250
                        enteredCR: 0
                      - sourceAssignmentName: Vision Comms RT
                        transactionTable: REAL TIME
                        transactionType: TYPE
                        transactionClass: CLASS
                        transactionRef: MSS90690
                        transactionID: 90989
                        parentTrxID: 90985
                        transactionDate: 01-JAN-2021
                        currencyCode: USD
                        attribute1: '01'
                        attribute2: '03'
                        attribute3: Service
                        enteredDR: 250
                        enteredCR: 0
                  
      responses:
        '201':
          description: Real Time Engine successfully run
          content:
            application/json:
              schema:
                type: object
                properties:
                  SAE:
                    type: array
                    items:
                      type: object
              examples:
                'success response':
                  value:
                    RTTOutbound:
                     - legalName: Vision Trading (US)
                       interfaceID: 9021
                       transactionRef: MSS90687
                       ICPrice: 0
                       quantity: 1
                       extended: 0
                       VTResultsAttribute1: MSS90687
                       VTResultsAttribute2: null
                       VTResultsAttribute3: null
                       VTResultsAttribute4: null
                       VTResultsAttribute5: null
                       VTResultsAttribute6: null
                       VTResultsAttribute7: null
                       VTResultsAttribute8: null
                       VTResultsAttribute9: null
                       VTResultsAttribute10: null
                       VTResultsAttribute11: null
                       VTResultsAttribute12: null
                       VTResultsAttribute13: null
                       VTResultsAttribute14: null
                       VTResultsAttribute15: null
                       VTResultsAttribute16: null
                       VTResultsAttribute17: null
                       VTResultsAttribute18: null
                       VTResultsAttribute19: null
                       VTResultsAttribute20: 1
                       VTResultsAttribute21: null
                       VTResultsAttribute22: null
                       VTResultsAttribute23: null
                       VTResultsAttribute24: null
                       VTResultsAttribute25: null
                       VTResultsAttribute26: null
                       VTResultsAttribute27: null
                       VTResultsAttribute28: null
                       VTResultsAttribute29: null
                       VTResultsAttribute30: null
                       VTResultsAttribute31: null
                       VTResultsAttribute32: null
                       VTResultsAttribute33: null
                       VTResultsAttribute34: null
                       VTResultsAttribute35: null
                       VTResultsAttribute36: null
                       VTResultsAttribute37: null
                       VTResultsAttribute38: null
                       VTResultsAttribute39: null
                       VTResultsAttribute40: null
                     - legalName: Vision Trading (US)
                       interfaceID: 9026
                       transactionRef: MSS90690
                       ICPrice: 0
                       quantity: 1
                       extended: 0
                       VTResultsAttribute1: MSS90690
                       VTResultsAttribute2: null
                       VTResultsAttribute3: null
                       VTResultsAttribute4: null
                       VTResultsAttribute5: null
                       VTResultsAttribute6: null
                       VTResultsAttribute7: null
                       VTResultsAttribute8: null
                       VTResultsAttribute9: null
                       VTResultsAttribute10: null
                       VTResultsAttribute11: null
                       VTResultsAttribute12: null
                       VTResultsAttribute13: null
                       VTResultsAttribute14: null
                       VTResultsAttribute15: null
                       VTResultsAttribute16: null
                       VTResultsAttribute17: null
                       VTResultsAttribute18: null
                       VTResultsAttribute19: null
                       VTResultsAttribute20: 1
                       VTResultsAttribute21: null
                       VTResultsAttribute22: null
                       VTResultsAttribute23: null
                       VTResultsAttribute24: null
                       VTResultsAttribute25: null
                       VTResultsAttribute26: null
                       VTResultsAttribute27: null
                       VTResultsAttribute28: null
                       VTResultsAttribute29: null
                       VTResultsAttribute30: null
                       VTResultsAttribute31: null
                       VTResultsAttribute32: null
                       VTResultsAttribute33: null
                       VTResultsAttribute34: null
                       VTResultsAttribute35: null
                       VTResultsAttribute36: null
                       VTResultsAttribute37: null
                       VTResultsAttribute38: null
                       VTResultsAttribute39: null
                       VTResultsAttribute40: null
        '400':
          description: Bad Request
        '200':
          description: A Real Time Engine error has occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  SAE:
                    type: array
                    items:
                      type: object
              examples:
                'error response':
                  value:
                    RTTOutbound:
                      content:
                        errorCode: 3502
                        errorMessage: Check Assignment Rules setup within the Assignment Control form. Also check the Tax Registration Lookup form
          headers:
            XX-ERROR-MSG:
              schema:
                type: string
              description: Real Time Engine error occurred
