openapi: 3.0.1
info:
  title: Engines WS APIs
  description: creation of engine data and running of the respective engine
  version: '0.1'
tags:
  - name: SAE
    description: Soft Assignment Engine
paths:
  /engines/sae:
    post:
      tags:
        - SAE
      description: Web Service to pass data to and run the Soft Assignment Engine        


      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                SAE:
                  type: array
                  items:
                    type: object
            examples:
              'sample':
                value:
                  SAEInbound:
                    trace: 'Y'
                    createRow: 'Y'
                    updateExistingRow: 'N'
                    currencyCode: USD
                    parentTrxID: '999992'
                    transactionID: '99999'
                    transactionRef: A-99999
                    transactionTable: MANUAL_REQ
                    transactionType: REQ
                    transactionClass: ALL
                    transactionDate: 04-JAN-2021
                    sourceAssignmentName: 'Test Harness'
                    attribute1: 1003
                    attribute2: 1009
                    attribute3: 1234
                    attribute4: Product
                    attribute5: AR
                    attribute6: US
                    attribute7: IT
                    attribute8: ''
                    attribute9: Standard-NL
                    attribute10: 48
      responses:
        '201':
          description: Soft Assignment Engine successfully run
          content:
            application/json:
              schema:
                type: object
                properties:
                  SAE:
                    type: array
                    items:
                      type: object
              examples:
                'success response':
                  value:
                    SAEOutbound:
                      transactionRef: A-99999
                      interfaceID: 0
                      sequence: 1
                      tradingSet: SAE Buy/Sell
                      tradingSetID: '101'
                      priceMethod: 'SAE Pricing General PM'
                      priceMethodID: 0
                      attributeID: 11011
                      ICPrice: 100
                      ICUnitPrice: 20
                      ICCurrency: USD
                      adjustmentRate: 0.04
                      adjustmentRateID: 17101089.07001
                      ownerCompany: '01'
                      partnerCompany: '103'
                      attribute1: 'USD'
                      attribute2: null
                      attribute3: null
                      attribute4: null
                      attribute5: null
                      attribute6: null
                      attribute7: null
                      attribute8: null
                      attribute9: null
                      attribute10: null
                      attribute11: null
                      attribute12: null
                      attribute13: null
                      attribute14: null
                      attribute15: null
                      attribute16: null
                      attribute17: null
                      attribute18: null
                      attribute19: null
                      attribute20: null
                      attribute21: null
                      attribute22: null
                      attribute23: null
                      attribute24: null
                      attribute25: null
                      attribute26: null
                      attribute27: null
                      attribute28: null
                      attribute29: null
                      attribute30: null
        '400':
          description: Bad Request
        '200':
          description: A Soft Assignment Engine error has occurred
          headers:
            XX-ERROR-MSG:
              schema:
                type: string
              description: Error The Assignment incomplete. Check Transaction Table and type  (12998)
