openapi: 3.0.1
tags:
  - name: JobStatuses
    description: Get Job Status

paths:
  /admin/JobStatuses/{Job_id}:
    get:
      tags:
        - JobStatuses
      description: Web Service to retrieve the status of a submitted job
      responses:
        '200':
          description: SUCCESS
          headers:
            XX-START-DATE:
              schema:
                type: string
              description: 2021-11-16 12:26:59
            XX-END-DATE:
              schema:
                type: string
              description: 2021-11-16 12:28:24
            XX-JOB-MESSAGE:
              schema:
                type: string
              description: JOB SUCCEEDED
        '400':
          description: Bad Request