openapi: 3.0.1
info:
  title: Admin WS APIs
  description: Web Services to perform admin tasks
  version: '0.1'
tags:
  - name: Jobs
    description: Submit a Scheduled Job

paths:
  /admin/Jobs:
    post:
      tags:
        - Jobs
      description: Web Service to submit a Job to the Scheduler

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Jobs:
                  type: array
                  items:
                    type: object
            examples:
              'sample':
                value:
                  ScheduleJob:
                    programName: 'XXCPGLENG'
                    userName: 'MSPRING'
                    arguments: '3,1098,0,,,,,,,,,,,,'
      responses:
        '201':
          description: Soft Assignment Engine successfully run
          content:
            application/json:
              schema:
                type: object
                properties:
                  SAE:
                    type: array
                    items:
                      type: object
              examples:
                'success response':
                  value:
                    SAEOutbound:
                      transactionRef: A-99999
                      interfaceID: 0
                      sequence: 1
                      tradingSet: SAE Buy/Sell
                      tradingSetID: '101'
                      priceMethodID: 0
                      attributeID: 11011
                      ownerCompany: '01'
                      partnerCompany: '103'
        '400':
          description: Bad Request
        '501':
          description: A Soft Assignment Engine error has occurred
          headers:
            XX-ERROR-MSG:
              schema:
                type: string
              description: Error The Assignment incomplete. Check Transaction Table and type  (12998)