openapi: 3.0.1
info:
  title: Admin WS APIs
  description: Web Services to perform admin tasks
  version: '0.1'
tags:
  - name: JobStatuses
    description: Get Job Status

paths:
  /admin/JobStatuses:
    post:
      tags:
        - JobStatuses
      description: Web Service to retrieve the status of a submitted job

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                submitJob:
                  type: array
                  items:
                    type: object
            examples:
              'sample':
                value:
                  ScheduleJob:
                    programName: 'Y'
                    userName: 'MSPRING'
                    argument1: '3'
                    argument2: '1098'
                    argument3: '0'
                    argument4: '~NULL~'
                    argument5: '~NULL~'
                    argument6: '~NULL~'
                    argument7: '~NULL~'
                    argument8: '~NULL~'
                    argument9: '~NULL~'
                    argument10: '~NULL~'
                    argument11: '~NULL~'
                    argument12: '~NULL~'
                    argument13: '~NULL~'
                    argument14: '~NULL~'
                    argument15: '~NULL~'
      responses:
        '201':
          description: Soft Assignment Engine successfully run
          content:
            application/json:
              schema:
                type: object
                properties:
                  SAE:
                    type: array
                    items:
                      type: object
              examples:
                'success response':
                  value:
                    SAEOutbound:
                      transactionRef: A-99999
                      interfaceID: 0
                      sequence: 1
                      tradingSet: SAE Buy/Sell
                      tradingSetID: '101'
                      priceMethodID: 0
                      attributeID: 11011
                      ownerCompany: '01'
                      partnerCompany: '103'
        '400':
          description: Bad Request
        '501':
          description: A Soft Assignment Engine error has occurred
          headers:
            XX-ERROR-MSG:
              schema:
                type: string
              description: Error The Assignment incomplete. Check Transaction Table and type  (12998)